### ISSUE TITLE
Saknar hastighetsbegränsning vid Abborrkroken

### ISSUE THREAD

**Issue by marcusz** [PeterBjork12/Hastighetsbegr_SvenskaVatten#1]
<img width="1233" alt="Screenshot 2022-05-17 at 19 44 32" src="https://user-images.githubusercontent.com/1104918/168877087-f480d014-5903-4433-ac4d-54062efd4ee6.png">

Den är en sådan lurig som bara gäller delar av året

**Comment by PeterBjork12** [comment]
Hej, då var denna inskriven.. Hittade hastighetsbegränsningen i 01FS 2012:70
